global:
  imagePullSecret:
    name: container-registry
  domain: null
srv:
  bindings:
    auth:
      serviceInstanceName: xsuaa
    db:
      fromSecret: cpapp-db
  image:
    repository: <your-container-registry>/cpapp-srv
    tag: latest
  resources:
    limits:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
    requests:
      cpu: 100m
      ephemeral-storage: 1G
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: cpapp
    role-collections:
      - description: Manage Risks
        name: RiskManager
        role-template-references:
          - '$XSAPPNAME.RiskManager'
      - description: View Risks
        name: RiskViewer
        role-template-references:
          - '$XSAPPNAME.RiskViewer'
  config: xs-security.json
hana_deployer:
  image:
    repository: <your-container-registry>/cpapp-hana-deployer
    tag: latest
  bindings:
    hana:
      fromSecret: cpapp-db
